image:
  repository: lip13/optirisk
  tag: latest
  pullPolicy: Always
  containerPort: 8000
  nodePort: 30085
db:
  port: 5432
  name: optirisk-db
  secretName: postgres-secret 
  userKey: postgresuser
  passwordKey: postgrespassword
openai:
  secretName: openiakey-secret  
  key: openiakey
replicaCount: 3
securityContext: {}