apiVersion: apps/v1
kind: Deployment
metadata:
  name: optirisk-backend-dev-pod
  namespace: optirisk
  labels:
    app: optirisk-backend-dev-pod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: optirisk-backend-dev-pod
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: optirisk-backend-dev-pod
    spec:
      containers:
        - name: optirisk-backend-dev-pod
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          env:
            
      imagePullSecrets:
            - name: regcred