apiVersion: apps/v1
kind: Deployment
metadata:
  name: optirisk-backend-deploy
  namespace: optirisk
  labels:
    app: optirisk-backend-dev-pod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: optirisk-backend-dev-pod
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: optirisk-backend-dev-pod
    spec:
      restartPolicy: Always
      containers:
        - name: optirisk-backend-dev-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          env:
            - name: SECRET_KEY
              value: django-insecure-ean0&kgpx+&^36@@h7dmnngyc0=cjraiadzt5#46uw*wslep=e
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: 173.212.234.15,api-optirisk.paullence.link
            - name: FRONTLINK
              value: http://localhost:5173
            - name: APPNAME
              value: OPTIRISK
            - name: NAME
              value: {{ .Values.db.name }}
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: {{ .Values.db.userKey }} 
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: {{ .Values.db.passwordKey }}
            - name : HOST
              value: optirisk-backend-postgres
            - name: PORT
              value: "{{ .Values.db.port }}"
            - name: CORS_ALLOWED_ORIGINS
              value: http://localhost:5173
            - name: ACCESS_TOKEN_LIFETIME
              value: "60"
            - name: REFRESH_TOKEN_LIFETIME
              value: "1"
            - name: DEFAULT_FROM_EMAIL
              value: ptrece8@gmail.com
            - name: EMAIL_BACKEND
              value: django.core.mail.backends.smtp.EmailBackend
            - name:  EMAIL_HOST
              value: smtp.gmail.com
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_USE_TLS
              value: "True"
            - name: EMAIL_HOST_USER
              value: ptrece8@gmail.com
            - name: EMAIL_HOST_PASSWORD
              value: "vtsa jzph celo ydpm"
            - name: CLOUDINARY_CLOUD_NAME
              value: dxb4y413d
            - name: CLOUDINARY_API_KEY
              value: "746142781291887"
            - name: CLOUDINARY_API_SECRET
              value: N7Wd9FtDt-oS3mIivW3ldHFQWKU
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openai.secretName }}
                  key: {{ .Values.openai.key }}
        
