apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: optirisk
spec:
  ingressClassName: nginx
  rules:
    - host: api.optirisk.paullence.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: optirisk-backend-dev-service
                port:
                  name: http
    - host: www.api.optirisk.paullence.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: optirisk-backend-dev-service
                port:
                  name: http
