apiVersion: v1
kind: Service
metadata:
    name: optirisk-backend-dev-service
    namespace: optirisk
spec:
    ports:
        - name: http-api
          port: 8003
          targetPort: {{ .Values.image.containerPort }}
    selector:
        app: optirisk-backend-dev-pod