apiVersion: v1
kind: Service
metadata:
    name: optirisk-backend-dev-service
    namespace: optirisk
spec:
    ports:
        - name: http
          port: 8003
          targetPort: {{ .Values.image.containerPort }}
          nodePort: {{ .Values.image.nodePort }}
    type: NodePort
    selector:
        app: optirisk-backend-dev-pod