apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: optirisk-backend-deploy
  namespace: argocd
spec:
  destination:
    namespace: optirisk
    server: https://kubernetes.default.svc
  project: optirisk
  source:
    helm:
      parameters:
        - name: image.repository
          value: lip13/optirisk
        - name: image.tag
          value: e86c870bf11e35ec9f05489c2fb843c8e509b003
    path: helm/optirisk-backend-dev
    repoURL: https://github.com/Pauller13/optirisk.git
    targetRevision: helm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
